### ISSUE TITLE
V3 - Checklist

### ISSUE THREAD

**Issue by christianmalek** [christianmalek/vuex-rest-api#104]
This list is for myself to see what I still have to implement for version 3.

- [ ] **add tests** 🐛 
- [ ]  integrate deployment pipeline (CI)
- [ ] improve readme
- [ ] simplify adding resources (actions)
- [ ] make baseUrl changeable after creating store (just set baseUrl of axios instance)
- [ ] make default error state configurable
- [ ] add option to don't change state if error happens
- [ ] make `getStore({ createStateFn: true })` the default
- [ ] add logo
- [ ] implement caching (see #79)
- [ ] implement the possibility to cancel requests (see #79)
- [ ] implement the possibilty to access params in onSuccess, onError fn (see #79)
- [ ] custom pre-flight validation methods (see https://github.com/christianmalek/vuex-rest-api/issues/54#issuecomment-375934098)
  - integration with a JSON Schema validator e.g. [AJV](https://github.com/epoberezkin/ajv)
- [ ] make requests cancellable (see https://github.com/christianmalek/vuex-rest-api/issues/54#issuecomment-454217082)
- [ ] make endpoints mappable via object/config file (see https://github.com/christianmalek/vuex-rest-api/issues/54#issuecomment-376005856)
- [ ] allow easy customization of store object, that you don't have to use Object.assign() anymore after creating the store object
- [ ] check usage of namespaces
- [ ] add alternative way of adding actions (see #59)
- [ ] add option to disable error throwing (is this really helpful?)
- [ ] add global `onError` interceptor that can be overridden at resource entity level (see https://github.com/christianmalek/vuex-rest-api/issues/54#issuecomment-391183111)
- [ ] add `state.loaded.<propertyName>` to know if state was loaded at least once
- [ ] add `Axios.requestConfig.transformRequest` method to the resource action options (see #77)
- [ ] add explicit queryParams (see #44)
- [ ] use option parameter instead of multiple parameters (see https://github.com/christianmalek/vuex-rest-api/issues/84#issuecomment-419230941)
- [ ] support Fetch API (see #93)
- [ ] make requests cancel each other by demand (see https://github.com/christianmalek/vuex-rest-api/issues/54#issuecomment-454217082)
- [ ] make `error` and `pending` properties optional (see #95)
- [ ] add json:api support
- [ ] add information how to handle errors in documentation (see #105)
- [ ] make it possible to avoid rejection of promise when interceptor in axios or onError is set (see #105)

**Comment by pchisholm** [comment]
Hello,

I'm using vuex-rest-api in a work project and am wondering what the status on v3 is? In particular I'm wondering about the request cancellation feature.

I've run into a situation where I need it and I don't see a way to do this at the moment without modifying the library (was thinking about storing a `CancelToken` in `ActionParamsBody` and then setting it in the config that gets prepped in `requestFn` as a quick solve).

`params` and `data` are also both properties of `AxiosRequestConfig` - why not do a straight pass through so requests can be fully configured on the fly? I think that would still play okay with the way `requestConfig` is currently set for an action.

I'd be happy to help out with a PR if this would be a welcome change.

Thanks!

**Comment by christianmalek** [comment]
@pchisholm Hello and thank you for your interest in this project!

Unfortunately, the project is not being developed further at the moment. A version 3 does not exist yet and there is no date planned for when the project will be continued.

You are welcome to submit a PR. They are always welcome.
